---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hermes-secrets
  namespace: hermes
spec:
  encryptedData:
    ANTHROPIC_API_KEY: AgDAwjXkGDnqpmua63nS1fnIVGL9t+IYEgj7GPO3A93JcMKF6DJWj+iqZQSTtu6RAkg34cepiG7JglODQoVG6r+XJhkvsO3UNh4xAcYzcqRo68BaBDNdiT/+ODU5WXztqOSnmLlp06gZATZcOu50cDH6aCCudLV2IBz/Pc98xy+0XFcPndNXVVVFWW6GDO58lRVC5VAnULR0lx/99Xl1JgBslU3dv7c7S7MCpfnlPsaSrw4Sy6Lo8xA+F3XTfmJGtO2eqTGCo3I67yT2i07NFuvB3MYc3sEQKehAcqRQIVMikWNRwxE4XYSrXNWnYYC4HzYi0xFESIR9Z5ka3BQwS/s/3AhbNEsYajXamwmVxX1xnAkxvdP7xZVfgSNKWw/wPjYn7ptivFrFaLl9tC4IleKRk5yQOqjZgjU9PmKTuQyK2dnrqzdKh098HzmAs7CwcyJyzNo88vdyZ9eOM7owV9cw9WNppWEAo0AYr4g1rPxo5s1WbYeNTkIwmJZfmvN3EZJeP1qZMYasycVECi0vptOWZ6pXox/bzKwAWmmM9TCacO50xM6j66ljTBhAw8DrR7neG/gKlQ76+DZJ/9WTXgiBJigIIdvrdbjziRZ968yUvgitS78RLCKHp+v8NgKBbcbQ9bt5YHee8X2xvVB0TuJGFBSPnoNofzPKcpQLiNHCN7opNP8Ef9CZWeqlvlG73wTLdUIAYB1gh9dqtxjqD7yiBXdbKk/VPir1S2VanirhcSnaCVDIrxEIekQb3cHyK2a2uqtfeggIH7yUYre3KZPSXxGg77Cg7+9LPmWyucNkRFI0sCtumd+hGTmhP+U2qpguK0JuYjBWvHObzYQ=
  template:
    metadata:
      name: hermes-secrets
      namespace: hermes
    type: Opaque
