---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-api-secret
  namespace: mlops
spec:
  encryptedData:
    api-secret-key: AgDAqYdN+Is3HfIvV1uKU89s/HlDgkzRa8cizmYA5tXUrQW/0x6KI5PC/EG20eUir9Awkgs1ApUM4af3PLWioObOdoKn0OGIDwRrEorOm93i2mo0mEyXFQbtEEUD89hWzR8Y7AnCR8r3XR6pf2n9jxGjghEkKk5RtbiOeYjIdFrsmlKoYxuFWbvMXW/SQlg350Ds9dsQ9MW2VTX2UvoY64jLn9NbufhPyRcAyf72g/XLl7zb0cO15cwduN8FzKW4EMuqdE/yv+hhhOtHQApVQiORdlkAOSJsYgZDuDN270haXbJjrAki4HA8mf97fwbVK1xTm1FZdG8W0Yojxp97nsSyawiatX7ig/4IClHrM9qSuYESCKJbD9Qq5cudBwXmyfeZnOWgsiTbJYfjYxx4wWF6pOSZ99BjZAMtTh8td8bAuX+MMPPsyZQRyZuCyuIWxEu2H4l1YOzNLjoUg09llH0nCrlugFqPzYQeTC9QyWo1M0KACmuJcozhABeYcKbwsHWYItpEk5c1sqnu1WEygU8Lx5BHawAqTlTIHdpoHYBGmv4I5BqS/BaRB4WdUVneQ7UF/NPZRhVDvDu9d3CWYFG051NxUvPcz5LqwCThJC6bRfqD9E8olGV089s+/UQcunsZPHo6idjW0PbyhtURGr3URnN7Tq9PlwPxeGO+bP4+ku19Wv9U6CpDxuUcMxCwDwP8KtChKodwFN7Y4j7hvMxUbjG+llDVD0Lu9/D5WAVcrQ==
  template:
    metadata:
      name: airflow-api-secret
      namespace: mlops
    type: Opaque
